"""Command line entry point: ``python -m jevbert serve|init-env|fetch-model``."""

from __future__ import annotations

import argparse
import logging
import os
import secrets
import sys
from pathlib import Path

import uvicorn

from jevbert import __version__
from jevbert.api.app import create_app
from jevbert.config import API_KEYS_ENV, ConfigurationError, load_settings
from jevbert.fetch import fetch_model
from jevbert.inference.registry import build_registry

#: One line per record; the access logger writes a complete JSON object as its message.
_LOG_FORMAT = "%(message)s"

_ENV_TEMPLATE = """\
# Generated by `python -m jevbert init-env`. Keep this file out of version control.
{env}={key}
"""


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="jevbert", description="JevBERT P0.5 PoC server")
    parser.add_argument("--version", action="version", version=__version__)
    subcommands = parser.add_subparsers(dest="command", required=True)

    serve = subcommands.add_parser("serve", help="run the API server")
    serve.add_argument("--config", required=True, help="path to the YAML configuration")
    serve.add_argument("--host", default=None, help="override the configured bind host")
    serve.add_argument("--port", type=int, default=None, help="override the configured port")
    serve.add_argument("--log-level", default="info")

    init_env = subcommands.add_parser("init-env", help="write a .env holding a new API key")
    init_env.add_argument("--path", default=".env", help="destination file (default: .env)")

    fetch = subcommands.add_parser("fetch-model", help="download the pinned model revision")
    fetch.add_argument("--manifests-dir", default="manifests", help="default: manifests")
    fetch.add_argument("--models-dir", default="models", help="default: models")

    args = parser.parse_args(argv)
    logging.basicConfig(stream=sys.stderr, level=logging.INFO, format=_LOG_FORMAT)

    if args.command == "serve":
        return _serve(args)
    if args.command == "init-env":
        return _init_env(Path(args.path))
    return fetch_model(Path(args.manifests_dir), Path(args.models_dir))


def _serve(args: argparse.Namespace) -> int:
    try:
        settings = load_settings(args.config)
        registry = build_registry(settings)
    except ConfigurationError as exc:
        print(f"jevbert: {exc}", file=sys.stderr)
        return 2

    app = create_app(settings, registry)
    uvicorn.run(
        app,
        host=args.host or settings.serving.host,
        port=args.port or settings.serving.port,
        log_level=args.log_level,
        access_log=False,  # The middleware already logs one structured line per request.
    )
    return 0


def _init_env(path: Path) -> int:
    """Write a new key, or refuse if the file is already there.

    Created with ``O_EXCL`` rather than an ``exists()`` check followed by a write: the
    check and the write are not one step, and losing that race would overwrite the
    operator's own credential. The mode is set at creation time so the secret is never
    briefly world readable (S-L5).
    """
    key = secrets.token_urlsafe(32)
    try:
        descriptor = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    except FileExistsError:
        print(f"jevbert: {path} already exists; it was left unchanged.", file=sys.stderr)
        return 1
    except OSError as exc:
        print(f"jevbert: cannot create {path}: {type(exc).__name__}", file=sys.stderr)
        return 1
    with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
        handle.write(_ENV_TEMPLATE.format(env=API_KEYS_ENV, key=key))
    print(f"jevbert: wrote a new API key to {path}. Keep it secret and out of git.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
