"""Command line entry point: ``python -m jevbert serve|init-env|fetch-model``."""

from __future__ import annotations

import argparse
import logging
import secrets
import sys
from pathlib import Path

import uvicorn

from jevbert import __version__
from jevbert.api.app import create_app
from jevbert.config import API_KEYS_ENV, ConfigurationError, load_settings
from jevbert.inference.registry import build_registry

#: One line per record; the access logger writes a complete JSON object as its message.
_LOG_FORMAT = "%(message)s"

_ENV_TEMPLATE = """\
# Generated by `python -m jevbert init-env`. Keep this file out of version control.
{env}={key}
"""


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="jevbert", description="JevBERT P0.5 PoC server")
    parser.add_argument("--version", action="version", version=__version__)
    subcommands = parser.add_subparsers(dest="command", required=True)

    serve = subcommands.add_parser("serve", help="run the API server")
    serve.add_argument("--config", required=True, help="path to the YAML configuration")
    serve.add_argument("--host", default=None, help="override the configured bind host")
    serve.add_argument("--port", type=int, default=None, help="override the configured port")
    serve.add_argument("--log-level", default="info")

    init_env = subcommands.add_parser("init-env", help="write a .env holding a new API key")
    init_env.add_argument("--path", default=".env", help="destination file (default: .env)")

    subcommands.add_parser("fetch-model", help="download the pinned model revision")

    args = parser.parse_args(argv)
    logging.basicConfig(stream=sys.stderr, level=logging.INFO, format=_LOG_FORMAT)

    if args.command == "serve":
        return _serve(args)
    if args.command == "init-env":
        return _init_env(Path(args.path))
    return _fetch_model()


def _serve(args: argparse.Namespace) -> int:
    try:
        settings = load_settings(args.config)
        registry = build_registry(settings)
    except ConfigurationError as exc:
        print(f"jevbert: {exc}", file=sys.stderr)
        return 2

    app = create_app(settings, registry)
    uvicorn.run(
        app,
        host=args.host or settings.serving.host,
        port=args.port or settings.serving.port,
        log_level=args.log_level,
        access_log=False,  # The middleware already logs one structured line per request.
    )
    return 0


def _init_env(path: Path) -> int:
    if path.exists():
        print(
            f"jevbert: {path} already exists; it was left unchanged.",
            file=sys.stderr,
        )
        return 1
    key = secrets.token_urlsafe(32)
    path.write_text(_ENV_TEMPLATE.format(env=API_KEYS_ENV, key=key), encoding="utf-8")
    print(f"jevbert: wrote a new API key to {path}. Keep it secret and out of git.")
    return 0


def _fetch_model() -> int:
    # Phase 2 implements the pinned-revision download and the manifest hash recording
    # (ADR-014). Failing loudly beats pretending the weights are in place.
    print(
        "jevbert: fetch-model is not implemented yet (phase 2). Until then the server "
        "can only serve bundles whose weights and manifest are already present.",
        file=sys.stderr,
    )
    return 3


if __name__ == "__main__":
    raise SystemExit(main())
